// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VigilanceFire.Data;

#nullable disable

namespace VigilanceFire.Migrations
{
    [DbContext(typeof(VigilanceFireContext))]
    [Migration("20240912160610_Evacuation_Instructions")]
    partial class Evacuation_Instructions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VigilanceFire.Models.Administrator", b =>
                {
                    b.Property<int>("admin_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_Id");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.Alert", b =>
                {
                    b.Property<int>("alert_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("alert_Id"));

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("condition")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("alert_Id");

                    b.ToTable("Alert", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.Cameras", b =>
                {
                    b.Property<int>("Cam_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cam_Id"));

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime2");

                    b.HasKey("Cam_Id");

                    b.ToTable("Cameras", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.Evacuation_Instructions", b =>
                {
                    b.Property<int>("evacuation_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("evacuation_Id"));

                    b.Property<string>("instruction_text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("evacuation_Id");

                    b.ToTable("Evacuation_Instructions", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.GasController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("GasController", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.Main_Dashboard", b =>
                {
                    b.Property<int>("mainDP_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mainDP_Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mainDP_Id");

                    b.ToTable("Main_Dashboard", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.User", b =>
                {
                    b.Property<int>("user_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Administratoradmin_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_Id");

                    b.HasIndex("Administratoradmin_Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("VigilanceFire.Models.User", b =>
                {
                    b.HasOne("VigilanceFire.Models.Administrator", null)
                        .WithMany("users")
                        .HasForeignKey("Administratoradmin_Id");
                });

            modelBuilder.Entity("VigilanceFire.Models.Administrator", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
